version: "3.9"

services:
  db: # pg-tasks
    image: postgres:9.6
    container_name: pg-tasks
    environment:
      POSTGRES_DB: tasks
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  
