version: "3.9"

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    entrypoint: /bin/bash -c "mv /usr/local/tomcat/webapps /usr/local/tomcat/webapps2; mv /usr/local/tomcat/webapps.dist /usr/local/tomcat/webapps; cp /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml; catalina.sh run"
    ports:
      - 8081:8080
    volumes:
      - ./config/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./config/tomcat/context.xml:/tmp/context.xml
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
